### ISSUE TITLE
Test against WordPress 5.8

### ISSUE THREAD

**Issue by jeffpaul** [10up/simple-new-post-emails#40]
**Is your enhancement related to a problem? Please describe.**
Once WordPress 5.8 is released, we'll want to test Simple New Post Emails to see if any incompatibility issues arise.

**Describe the solution you'd like**
- [x] test Simple New Post Emails on WordPress 5.8
- [ ] open issues for any incompatibilities noted in testing
- [ ] resolve issues identified in testing
- [ ] bump "tested up to" version
- [ ] if code changes needed due to incompatibilities, ship a plugin release, otherwise use "Plugin asset/readme update" action to update "tested up to" version on .org repo

**Designs**
n/a

**Describe alternatives you've considered**
none

**Additional context**
Related: #29, #38.

**Comment by phpbits** [comment]
@jeffpaul I tested the plugin briefly in a single site installation that's using WordPress 5.8. I did not experience any issues, both the user setting and the widget are working as expected. Thanks!

**Comment by jeffpaul** [comment]
Awesome, thank you @phpbits!  @ChrisHardie do you want to handle the tested-up-to bump on this one?
